services:
  mysql:
    image: mysql:8.0
    container_name: bankapp-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: bankapp_db
      MYSQL_USER: bankuser
      MYSQL_PASSWORD: bankpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: ${DOCKERHUB_USERNAME}/bankapp:${IMAGE_TAG}  # Replace with your Docker Hub repo
    container_name: bankapp-backend
    restart: always
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: bankuser
      DB_PASSWORD: bankpassword
      DB_NAME: bankapp_db
    ports:
      - "8000:8000"

  frontend:
    image: poojabhavani08/bankapp-frontend:latest  # Replace with your Docker Hub repo
    container_name: bankapp-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_BACKEND_URL: http://backend:8000

volumes:
  mysql_data:
