name: CD - Deploy & DAST

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy to EC2 via SSH
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Create Deployment Directory
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: mkdir -p ~/bankapp

      - name: Copy docker compose file
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "docker-compose.yml"
          target: "~/bankapp"

      - name: Pull and Deploy Docker Compose
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            cd ~/bankapp
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
            docker volume create mysql-data
            docker volume create ollama-data
            docker compose down --remove-orphans
            docker compose pull
            docker compose up -d --build

  dast:
    name: DAST - OWASP ZAP Baseline Scan
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.15.0
        continue-on-error: true
        with:
          target: 'http://${{ secrets.EC2_HOST }}:8080'
          artifact_name: zapreport
          fail_action: false
          allow_issue_writing: false

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-dast-report
          path: report_html.html
